"""rework intake_reports: taken_at/recorded_at, drop is_late/prescription_id

Revision ID: 38fadde924fb
Revises: 51e0da194659
Create Date: 2026-07-01 14:47:36.194879

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38fadde924fb"
down_revision: str | Sequence[str] | None = "51e0da194659"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intake_reports", sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "intake_reports",
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_column("intake_reports", "confirmed_at")
    op.drop_column("intake_reports", "is_late")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intake_reports",
        sa.Column("is_late", sa.Boolean(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "intake_reports",
        sa.Column(
            "confirmed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("intake_reports", "recorded_at")
    op.drop_column("intake_reports", "taken_at")
    # ### end Alembic commands ###
