"""drop_timezone_from_users

Revision ID: 4b0b9cd951d2
Revises: 46a937daa5e2
Create Date: 2026-07-14 15:23:14.160094

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b0b9cd951d2"
down_revision: str | Sequence[str] | None = "46a937daa5e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("timezone", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
