"""drop prescription_id from intake_reports

Revision ID: 51e0da194659
Revises: 5234b5d19adf
Create Date: 2026-07-01 11:10:58.996262

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51e0da194659"
down_revision: str | Sequence[str] | None = "5234b5d19adf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("intake_reports_prescription_id_fkey"), "intake_reports", type_="foreignkey"
    )
    op.drop_column("intake_reports", "prescription_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intake_reports",
        sa.Column("prescription_id", sa.Uuid(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("intake_reports_prescription_id_fkey"),
        "intake_reports",
        "prescriptions",
        ["prescription_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
