"""create reminder_config and intake_reports

Revision ID: 5234b5d19adf
Revises: 7937bbb21eae
Create Date: 2026-07-01 10:35:56.007759

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5234b5d19adf"
down_revision: str | Sequence[str] | None = "7937bbb21eae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_config",
        sa.Column("morning_time", sa.Time(), nullable=False),
        sa.Column("day_time", sa.Time(), nullable=False),
        sa.Column("evening_time", sa.Time(), nullable=False),
        sa.Column("max_reminders", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "intake_reports",
        sa.Column("period", sa.Enum("MORNING", "DAY", "EVENING", name="whenslot"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=True),
        sa.Column(
            "confirmed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_late", sa.Boolean(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["prescription_id"], ["prescriptions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "period", "date", name="uq_intake_reports_user_period_date"),
    )
    op.create_index(op.f("ix_intake_reports_user_id"), "intake_reports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intake_reports_user_id"), table_name="intake_reports")
    op.drop_table("intake_reports")
    op.drop_table("reminder_config")
    sa.Enum(name="whenslot").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
