"""add last_export_at to users

Revision ID: 6c2975a57ecb
Revises: 723993d2e12b
Create Date: 2026-07-12 09:27:17.235452

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c2975a57ecb"
down_revision: str | Sequence[str] | None = "723993d2e12b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_export_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_export_at")
    # ### end Alembic commands ###
