"""create prescriptions and medication_items

Revision ID: 7937bbb21eae
Revises: 2154700cb0ca
Create Date: 2026-07-01 09:28:00.446348

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7937bbb21eae"
down_revision: str | Sequence[str] | None = "2154700cb0ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prescriptions",
        sa.Column("doctor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prescribed_on", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prescriptions_user_id"), "prescriptions", ["user_id"], unique=False)
    op.create_table(
        "medication_items",
        sa.Column("medicine", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("condition", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("when_slots", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dose_amount", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "dose_unit",
            sa.Enum("TABLET", "MG", "ML", "DROP", "MCG", "IU", name="doseunit"),
            nullable=True,
        ),
        sa.Column("freq_count", sa.Integer(), nullable=False),
        sa.Column("freq_period", sa.Integer(), nullable=False),
        sa.Column(
            "freq_period_unit",
            sa.Enum("HOUR", "DAY", "WEEK", name="freqperiodunit"),
            nullable=False,
        ),
        sa.Column("course_type", sa.Enum("ONGOING", "COURSE", name="coursetype"), nullable=False),
        sa.Column("course_start", sa.DateTime(), nullable=True),
        sa.Column("course_intakes", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["prescription_id"], ["prescriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("medication_items")
    op.drop_index(op.f("ix_prescriptions_user_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    sa.Enum(name="doseunit").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="freqperiodunit").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="coursetype").drop(op.get_bind(), checkfirst=True)
