"""add user_id foreign keys

Revision ID: 901b2b9941ba
Revises: 65876195c6de
Create Date: 2026-07-01 15:57:50.496833

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "901b2b9941ba"
down_revision: str | Sequence[str] | None = "65876195c6de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_measurements_user_id_users", "measurements", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_prescriptions_user_id_users", "prescriptions", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_reminder_config_user_id_users", "reminder_config", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_intake_reports_user_id_users", "intake_reports", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_intake_reports_user_id_users", "intake_reports", type_="foreignkey")
    op.drop_constraint("fk_reminder_config_user_id_users", "reminder_config", type_="foreignkey")
    op.drop_constraint("fk_prescriptions_user_id_users", "prescriptions", type_="foreignkey")
    op.drop_constraint("fk_measurements_user_id_users", "measurements", type_="foreignkey")
    # ### end Alembic commands ###
